# CONFIG_IOPMP=n
CONFIG_HW_STACK_PROTECTION=n
CONFIG_PMP_STACK_GUARD_MIN_SIZE=128
# CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.1.123"
# CONFIG_NET_CONFIG_MY_IPV4_ADDR="10.10.20.123"
# CONFIG_NET_CONFIG_MY_IPV4_GW="10.10.20.1"
CONFIG_MDIO=y
CONFIG_MDIO_SHELL=n

# CONFIG_COMPILER_OPT="-O3"
CONFIG_THREAD_ANALYZER=y
# CONFIG_NET_PHY_FORCE_100M=y
# CONFIG_NUM_COOP_PRIORITIES=0

CONFIG_NET_TC_THREAD_PRIO_CUSTOM=y
CONFIG_NET_TC_RX_THREAD_BASE_PRIO=5
CONFIG_NET_TC_TX_THREAD_BASE_PRIO=4
# CONFIG_NET_SOCKETS_SERVICE_THREAD_PRIO=6

CONFIG_NET_IPV6=n

# CONFIG_NET_BUF_RX_COUNT=256
# CONFIG_NET_BUF_TX_COUNT=256

# CONFIG_IDLE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SHELL_STACK_SIZE=2048
CONFIG_TIMESLICING=y
CONFIG_TIMESLICE_SIZE=0

# CONFIG_COMMON_LIBC_MALLOC=y
# CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=32768

# CONFIG_COMMON_LIBC_MALLOC=n
# CONFIG_NEWLIB_LIBC_MALLOC_LSQSH=y
# CONFIG_NEWLIB_LIBC_MALLOC_ARENA_SIZE=32768
