# Zephyr crypto disabled, only mbedtls tests
CONFIG_CRYPTO=n
CONFIG_CRYPTO_LINKEDSEMI_SHA256=n
CONFIG_CRYPTO_LINKEDSEMI_SHA512=n

CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_TIMING_FUNCTIONS=y
CONFIG_MINIMAL_LIBC=y

CONFIG_ENTROPY_GENERATOR=y

# mbedtls support
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_CUSTOM_MBEDTLS_CFG_FILE=y
CONFIG_MBEDTLS_CFG_FILE="config-linkedsemi-tls.h"

CONFIG_MBEDTLS_SHA224=y
CONFIG_MBEDTLS_SHA256=y

CONFIG_MBEDTLS_SHA384=y
CONFIG_MBEDTLS_SHA512=y

CONFIG_MBEDTLS_THREADING_LINKEDSEMI_ALT=y

# OTBN RSA support
CONFIG_SHA256_CLOCK_RESET=y
CONFIG_SHA512_CLOCK_RESET=y

CONFIG_DMA=y

# OTBN ECDSA support
CONFIG_MBEDTLS_ECP_C=y
CONFIG_MBEDTLS_ECDSA_C=y

CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=65536

CONFIG_MAIN_STACK_SIZE=32768


# linkedsemi cncryption acceleration
# sha256/sha512/sm3
CONFIG_MBEDTLS_SHA224_SHA256_SM3_LINKEDSEMI_HARDWARE_ALT=n
CONFIG_MBEDTLS_SHA256_SM3_LINKEDSEMI_OTBN_ALT=n
# ecdsa-p256r1 p384r1 sm2
CONFIG_MBEDTLS_ECDSA_SECP256R1_SECP384R1_SM2_LINKEDSEMI_OTBN_ALT=n
# hash
CONFIG_MBEDTLS_SHA384_SHA512_LINKEDSEMI_HARDWARE_ALT=n
CONFIG_MBEDTLS_SHA384_SHA512_LINKEDSEMI_OTBN_ALT=n
# AES/SM4 support
CONFIG_MBEDTLS_CIPHER_AES_LINKEDSEMI=n
CONFIG_MBEDTLS_SM4_LINKEDSEMI_HARDWARE_ALT=n
# RSA
CONFIG_MBEDTLS_RSA_LINKEDSEMI_OTBN_ALT=y

CONFIG_LS_OTBN_OPERATION_TIMEOUT_MS=60000