
# C++ 支持
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_CPP_EXCEPTIONS=y
CONFIG_CPP_RTTI=y
CONFIG_GLIBCXX_LIBCPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# 使用完整 newlib
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_NANO=n


# 栈空间
# 主线程栈大小（64KB，你的配置合理，保留）
CONFIG_MAIN_STACK_SIZE=65536

# PTHREAD栈配置2^19 = 512k
CONFIG_POSIX_PTHREAD_ATTR_STACKSIZE_BITS=19


# 内存池配置（关键：堆大小必须≥线程栈大小）
CONFIG_HEAP_MEM_POOL_SIZE=131072

# 调试
CONFIG_DEBUG=y
CONFIG_DEBUG_INFO=y
CONFIG_NO_OPTIMIZATIONS=y


# POSIX API
CONFIG_POSIX_API=y
CONFIG_PTHREAD=y
CONFIG_PTHREAD_KEY=y
CONFIG_PTHREAD_MUTEX=y
CONFIG_PTHREAD_COND=y
CONFIG_PTHREAD_BARRIER=y
CONFIG_PTHREAD_RWLOCK=y