# SPDX-License-Identifier: Apache-2.0

# RTC 子系统
CONFIG_RTC=y
CONFIG_RTC_INS5710C=y
#
## I2C 支持
CONFIG_I2C=y
# 开启打印日志（默认开启，确保控制台输出正常）
CONFIG_CONSOLE=y
CONFIG_SERIAL=y
#
## 日志配置
CONFIG_LOG=y
CONFIG_SERIAL=y
# I2C驱动日志级别：DEBUG级别，打印底层传输细节
CONFIG_I2C_LOG_LEVEL_DBG=y
# 可选：全局默认日志级别设为DEBUG
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_DEFAULT_LEVEL=4

