# SPDX-License-Identifier: Apache-2.0

# eMMC Coredump Test Configuration

# CONFIG_TEST=y
CONFIG_DEBUG_COREDUMP=y
CONFIG_DEBUG_COREDUMP_MEMORY_DUMP_THREADS=y
CONFIG_DEBUG_COREDUMP_MEMORY_DUMP_LINKER_RAM=y

# Select eMMC backend
CONFIG_DEBUG_COREDUMP_BACKEND_EMMC=y
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_MMC=y
CONFIG_LOG_MODE_IMMEDIATE=y
# FATFS for partition support
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_MULTI_PARTITION=y

# Logging
CONFIG_LOG=y

# Enable shell for debugging
CONFIG_SHELL=y
CONFIG_DEBUG_COREDUMP_SHELL=y
CONFIG_FILE_SYSTEM_SHELL=y
CONFIG_MAIN_STACK_SIZE=4000

# Stack protection
CONFIG_TEST_HW_STACK_PROTECTION=n