CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_CUSTOM_MBEDTLS_CFG_FILE=y
CONFIG_MBEDTLS_CFG_FILE="config-linkedsemi-tls.h"
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=4096

CONFIG_MBEDTLS_SHA224=y
CONFIG_MBEDTLS_SHA256=y

CONFIG_MBEDTLS_SHA384=y
CONFIG_MBEDTLS_SHA512=y

CONFIG_MBEDTLS_SHA224_SHA256_SM3_LINKEDSEMI_HARDWARE_ALT=y
# CONFIG_MBEDTLS_SHA256_SM3_LINKEDSEMI_OTBN_ALT=y

CONFIG_MBEDTLS_SHA384_SHA512_LINKEDSEMI_HARDWARE_ALT=y
# CONFIG_MBEDTLS_SHA384_SHA512_LINKEDSEMI_OTBN_ALT=y

CONFIG_MBEDTLS_THREADING_LINKEDSEMI_ALT=y
CONFIG_DMA=y
CONFIG_SHA256_CLOCK_RESET=y
CONFIG_TIMING_FUNCTIONS=y

CONFIG_MINIMAL_LIBC=y
CONFIG_MAIN_STACK_SIZE=32768
