CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=4096


# CONFIG_MBEDTLS_LOG_LEVEL_DBG=y
# CONFIG_MBEDTLS_LOG_LEVEL_DBG=y
# CONFIG_MBEDTLS_OTBN_LOG_LEVEL_DBG=y

CONFIG_CUSTOM_MBEDTLS_CFG_FILE=y
CONFIG_MBEDTLS_CFG_FILE="config-linkedsemi-tls.h"

# linkedsemi defined
CONFIG_MBEDTLS_CIPHER_AES_LINKEDSEMI=y # When opened, it uses the hardware encryption of linkedsemi

CONFIG_MBEDTLS_SHA224_SHA256_SM3_LINKEDSEMI_HARDWARE_ALT=y
# CONFIG_MBEDTLS_SHA256_SM3_LINKEDSEMI_OTBN_ALT=y

CONFIG_MBEDTLS_SHA384_SHA512_LINKEDSEMI_HARDWARE_ALT=y
# CONFIG_MBEDTLS_SHA384_SHA512_LINKEDSEMI_OTBN_ALT=y

CONFIG_MBEDTLS_SM4_LINKEDSEMI_HARDWARE_ALT=y
CONFIG_MBEDTLS_ECDSA_SECP256R1_SECP384R1_SM2_LINKEDSEMI_OTBN_ALT=y
CONFIG_MBEDTLS_THREADING_LINKEDSEMI_ALT=y

CONFIG_SM4_CLOCK_RESET=y
CONFIG_AES_CLOCK_RESET=y
CONFIG_SHA512_CLOCK_RESET=y
CONFIG_SHA256_CLOCK_RESET=y
CONFIG_MEBDTLS_LINKEDSEMI_OTBN_DELEGATION_CLIENT=n
CONFIG_MEBDTLS_LINKEDSEMI_OTBN_DELEGATION_SERVER=n




CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_MAIN_STACK_SIZE=40960
CONFIG_COMPILER_SAVE_TEMPS=y
CONFIG_DMA=y

# west build -p always -b lsqsh_evb@1os/lsqsh/cpu1 . -DCONF_FILE="boards/lsqsh_evb_cpu1_user_config.conf" -DDTC_OVERLAY_FILE="boards/lsqsh_evb_cpu1_user_config.overlay"